import type { MCPServer } from "#shared/types";

export default defineEventHandler((): MCPServer[] => {
  return [
    {
      id: "1",
      name: "filesystem",
      status: "online",
      transport: "stdio",
      endpoint: "npx @modelcontextprotocol/server-filesystem /tmp",
      toolsCount: 11,
      resourcesCount: 0,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:12:00Z",
    },
    {
      id: "2",
      name: "github",
      status: "online",
      transport: "stdio",
      endpoint: "npx @modelcontextprotocol/server-github",
      toolsCount: 26,
      resourcesCount: 0,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:10:00Z",
    },
    {
      id: "3",
      name: "postgres",
      status: "degraded",
      transport: "http",
      endpoint: "http://localhost:5433/mcp",
      toolsCount: 5,
      resourcesCount: 3,
      promptsCount: 1,
      lastSyncAt: "2026-04-20T07:55:00Z",
    },
    {
      id: "4",
      name: "slack",
      status: "online",
      transport: "http",
      endpoint: "http://localhost:3100/mcp",
      toolsCount: 8,
      resourcesCount: 0,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:09:00Z",
    },
    {
      id: "5",
      name: "brave-search",
      status: "online",
      transport: "stdio",
      endpoint: "npx @modelcontextprotocol/server-brave-search",
      toolsCount: 2,
      resourcesCount: 0,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:11:00Z",
    },
    {
      id: "6",
      name: "memory",
      status: "offline",
      transport: "stdio",
      endpoint: "npx @modelcontextprotocol/server-memory",
      toolsCount: 9,
      resourcesCount: 1,
      promptsCount: 0,
      lastSyncAt: "2026-04-19T23:40:00Z",
    },
    {
      id: "7",
      name: "puppeteer",
      status: "online",
      transport: "stdio",
      endpoint: "npx @modelcontextprotocol/server-puppeteer",
      toolsCount: 6,
      resourcesCount: 0,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:08:00Z",
    },
    {
      id: "8",
      name: "figma-remote",
      status: "online",
      transport: "http",
      endpoint: "http://localhost:3200/mcp",
      toolsCount: 18,
      resourcesCount: 2,
      promptsCount: 0,
      lastSyncAt: "2026-04-20T08:13:00Z",
    },
  ];
});
